### ISSUE TITLE
Upgrade to Micronaut 2.0.2

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-flyway#112]
Once Micronaut 2.0.2 is released, upgrade this module to use it.

This is necessary because it will bring `micronaut-sql` 3.0.x that is compiled with Micronaut 2 and fixes the issues with `@Factory` for old Micronaut 1.3.x version.

P.S: We could also use Micronaut 2.0.1 but as we are going to release Micronaut 2.0.2 really soon it is better to wait for that release.

**Comment by donbeave** [comment]
Hi, @ilopmar!

Do you need any help here? I can come with PR if you need it.

**Comment by ilopmar** [comment]
@donbeave sure, if you want to send the PR, please go ahead :-)
