### ISSUE TITLE
Micronaut with Flyway in GraalVM seems not running migrations

### ISSUE THREAD

**Issue by kmruiz** [micronaut-projects/micronaut-flyway#12]
Hello!

I'm trying to create a microservice template built in Micronaut, and I'm using the micronaut-flyway module to apply migrations to a PostgreSQL database.

I have a script that creates a GraalVM native-image from a shadowJar with all the flyway migrations. When I run the native image, it manages to connect to the database, however the flyway migrations are not run, so any endpoint will fail because the database doesn't exist.

However, when I run the shadowJar with any OpenJDK (tested 1.8 and 11) it works like a charm.

You can check the code (and run it) here:

https://github.com/kmruiz/micronaut-react-microfrontend-template

I tried to debug, but I can't find any stacktrace related to flyway.

### Environment Information

* **Operating System**: Windows 10 (Docker)
* **Micronaut Version**: 1.1.0
* **JDK Version**: GraalVM 19

Thank you for working on this module!

**Comment by bjuretic** [comment]
@ilopmar This will probably give you some hints what to look at: https://github.com/quarkusio/quarkus/tree/master/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/graal
