### ISSUE TITLE
Micronaut-flyway:2.1.1 does not work with Flyway-core:5.2.4

### ISSUE THREAD

**Issue by duongvu89** [micronaut-projects/micronaut-flyway#122]
We have a Postgres 9.3 database so we need to use Flyway-core:5.2.4.

Micronaut-flyway:2.0.1 worked fine with Flyway-core:5.2.4, when we upgraded Micronaut from 2.0.1 to 2.1.1, we encountered this error:

`Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.api.ResourceProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	... 75 more`

The configurations (worked with Micronaut 2.0.1, broken in 2.1.1) is:

`implementation "io.micronaut.flyway:micronaut-flyway"
   implementation("org.flywaydb:flyway-core") {
      version {
         strictly("5.2.4")
      }
   }`

**Comment by ilopmar** [comment]
I'm afraid that's not possible. Micronaut Flyway 2.1.1 is compatible with Flyway 6.5.4 and there were breaking changes between Flyway 5.x and 6.x.

We upgraded from Flyway 5 to 6 in Micronaut Flyway 2.0. The latest version that uses Flyway 5.2.4 in Micronaut Flyway 1.2.0.
