### ISSUE TITLE
JDBC url without explicit username is not honored.

### ISSUE THREAD

**Issue by meredrica** [micronaut-projects/micronaut-flyway#13]
Hello!
Seems like some uri parameters are lost on their way to flyway
With the following configuration:

```
postgres:
    reactive:
        client:
            uri: postgresql://dbhost:5432/database?user=user&password=pass&currentSchema=current
---
flyway:
    datasources:
        default:
            url: jdbc:${postgres.reactive.client.uri}
```

Flyway migrations are not triggered at all.

if we explicitly specify ``username`` and ``password`` in the config, flyway at least tries to connect but the ``currentSchema`` is lost anyway.
This is also visible in the log:

```
08:54:39.574 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 5.2.1 by Boxfuse
--
  | 08:54:40.658 [main] INFO  o.f.c.i.database.DatabaseFactory - Database: jdbc:postgresql://dbhost:5432/database (PostgreSQL 11.2)
  | 08:54:40.736 [main] WARN  o.f.c.i.database.base.Database - Flyway upgrade recommended: PostgreSQL 11.2 is newer than this version of Flyway and support has not been tested.
  | 08:54:40.767 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties] could not be loaded: Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
  | io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.configuration.dbmigration.flyway.FlywayConfigurationProperties] could not be loaded: Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
  | at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1164)
  | at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:235)
  | at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2293)
  | at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
  | at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
  | at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
  | at io.micronaut.runtime.Micronaut.run(Micronaut.java:288)
  | at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
  | at at.porscheinformatik.scshub.backend.Application.main(Application.java:11)
  | Caused by: org.flywaydb.core.api.FlywayException: Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
  | at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.doGetCurrentSchema(PostgreSQLConnection.java:64)
  | at org.flywaydb.core.internal.database.base.Connection.getCurrentSchema(Connection.java:92)
  | at org.flywaydb.core.Flyway.prepareSchemas(Flyway.java:1742)
  | at org.flywaydb.core.Flyway.execute(Flyway.java:1663)
  | at org.flywaydb.core.Flyway.migrate(Flyway.java:1341)
  | at io.micronaut.configuration.dbmigration.flyway.AbstractFlywayMigration.runFlyway(AbstractFlywayMigration.java:80)
  | at io.micronaut.configuration.dbmigration.flyway.AbstractFlywayMigration.run(AbstractFlywayMigration.java:70)
  | at io.micronaut.configuration.dbmigration.flyway.AlternativeMigrationRunner.onCreated(AlternativeMigrationRunner.java:62)
  | at io.micronaut.configuration.dbmigration.flyway.AlternativeMigrationRunner.onCreated(AlternativeMigrationRunner.java:40)
  | at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1523)
  | at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
  | at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1741)
  | at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1162)
  | ... 8 common frames omitted
```
The docs don't mention currentSchema properties.
Note that we:
* don't have datasource properties since we use reactive postgres
* reuse the postgres connection string by property reference

**Comment by ilopmar** [comment]
At this moment Flyway integration doesn't support defining the datasource using the postgres reactive client, that's why the migration is not triggered.
Can you please a sample application so I can take a look?

**Comment by meredrica** [comment]
@ilopmar we are just referencing the jdbc url. it's the same when i just add it under url like this:
``url: postgresql://dbhost:5432/database?user=user&password=pass&currentSchema=current``
seems like all the query params ``?user=user&password=pass&currentSchema=current`` in the jdbc url are lost. if we don't explicitly state username/password, flyway doesn't even try.

**Comment by ilopmar** [comment]
So, basically you have 2 options to configure Flyway:
- Use a `DataSource`
- Use `username`, `password` and `url`

If there is any `DataSource` with the same qualifier as the Flyway configuration, then it is used for the migrations. In your case there is not because Postgres-reactive doesn't create any DataSource.  
The other approach is using `username`, `password` and `url`, which is the one you are using. In this case Micronaut is using that but is failing for other reason. I'll take a look.

**Comment by meredrica** [comment]
ah, now I get it. I'll try to configure with a jdbc url and check if it works.

**Comment by ilopmar** [comment]
If you want to debug something, this is were the configuration is retrieved and the Datasource is created and used in Flyway: https://github.com/micronaut-projects/micronaut-flyway/blob/5d95efca103582643e85f70e19fb29e0675763b1/flyway/src/main/java/io/micronaut/configuration/dbmigration/flyway/AlternativeMigrationRunner.java#L61

**Comment by meredrica** [comment]
I found the issue. [Here](https://github.com/micronaut-projects/micronaut-flyway/blob/5d95efca103582643e85f70e19fb29e0675763b1/flyway/src/main/java/io/micronaut/configuration/dbmigration/flyway/FlywayConfigurationProperties.java#L192) is the check on whether there is an alternative datasource and it will return false if no username is specified. I don't think this is good as username/password can be set in the JDBC url (at least for postgres).
The Information is not lost by the way, flyway removes the query path so the password etc is not logged.
