### ISSUE TITLE
Upgrade BOM to Flyway 6

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-flyway#19]
Flyway 5.x has some issues with newer MariaDB JDBC drivers (>= 2.4.x). Please upgrade Flyway to version 6.x

Issues are:

- https://github.com/flyway/flyway/issues/2339
- https://github.com/flyway/flyway/issues/2481

**Comment by saw303** [comment]
@jameskleeh  I cannot find any information to this at the Flyway blog https://flywaydb.org/blog/flyway-6.0.0

But I manually upgraded a Micronaut 1.2.5 app to Flyway 6.0.7 by overwriting the fly-core version

```groovy
dependency 'org.mariadb.jdbc:mariadb-java-client:2.5.0'
dependency 'org.flywaydb:flyway-core:6.0.7'
```

and the application started with Flyway 6 and no problems.

**Comment by jameskleeh** [comment]
@saw303 As can be seen here https://flywaydb.org/documentation/releaseNotes#6.0.0 with the section title "Incompatible changes", there are breaking changes between 5.x and 6.x. In that case we would usually require a 2.x release of flyway. One would have to look at the breaking changes and see if they would have any impact on our use case. If not then it could go into a 1.x release.

**Comment by saw303** [comment]
@jameskleeh are you plan to integration this in the upcoming Micronaut 2.0 M2 release?

**Comment by morki** [comment]
@ilopmar can we release new major version with flyway 6, or how can we resolve this breaking change issue?

**Comment by ilopmar** [comment]
@morki yes, I'll upgrade Flyway to the latest version for Micronaut 2.

**Comment by vmj** [comment]
Maybe my eyes are crossed but `micronaut-flyway:2.0.0.RC1` still has dependency on `flyway-core-5.2.4`: https://search.maven.org/artifact/io.micronaut.configuration/micronaut-flyway/2.0.0.RC1/jar

**Comment by ilopmar** [comment]
@vmj I've just created a new Micronaut 2.0.0.RC2 application using launch.micronaut.io with `flyway` feature and get the dependency report:
```
\--- io.micronaut.flyway:micronaut-flyway -> 2.0.0.RC1
     +--- org.flywaydb:flyway-core:6.4.3
     +--- io.micronaut:micronaut-management -> 2.0.0.RC2
     |    +--- org.slf4j:slf4j-api:1.7.26
     |    +--- io.micronaut:micronaut-router:2.0.0.RC2 (*)
     |    \--- io.micronaut:micronaut-runtime:2.0.0.RC2 (*)
     \--- io.micronaut.sql:micronaut-jdbc:2.3.0 -> 2.3.4
          \--- io.micronaut:micronaut-inject:1.3.5 -> 2.0.0.RC2 (*)
```

You can see that the right version is used.

**Comment by vmj** [comment]
Thanks, @ilopmar !  I guess the difference is the usage of boms.  My project isn't using them, at least not yet.

I tested with this `build.gradle` in an empty directory:

```
plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.micronaut.configuration:micronaut-flyway:2.0.0.RC1"
}
```

Then `gradle dependencies |grep flyway-core` shows the 5.x version. I can workaround that with adding direct dependency on 6.x, for now.

**Comment by ilopmar** [comment]
Yep, using our BOM enforces the right versions.

**Comment by ilopmar** [comment]
BTW @vmj the group here is not correct: https://search.maven.org/artifact/io.micronaut.configuration/micronaut-flyway/2.0.0.RC1/jar
We moved to `io.micronaut.flyway` and it shows the right dependency: https://search.maven.org/artifact/io.micronaut.flyway/micronaut-flyway/2.0.0.RC1/jar

**Comment by vmj** [comment]
Well that explains!  I will also need to use jcenter, it seems.  Gradle didn't find `io.ktor:ktor-bom:1.3.2` from mavenCentral.

**Comment by ilopmar** [comment]
Yes, they don't publish the artifacts to Central yet. We have an open issue there to request the publish to both JCenter and Maven Central: https://github.com/ktorio/ktor/issues/1942
