### ISSUE TITLE
Unable to configure flyway.datasources.*.ignore-migration-patterns

### ISSUE THREAD

**Issue by ivanmartinvalle** [micronaut-projects/micronaut-flyway#309]
### Expected Behavior

[flyway.datasources.*.ignore-migration-patterns.ignore-migration-patterns](https://flywaydb.org/documentation/configuration/parameters/ignoreMigrationPatterns) `"*:missing"` should allow us to ignore missing migrations, which is useful for concurrent development of different features.

### Actual Behaviour

When starting the application which runs migrations

```
java.lang.NullPointerException: null\n\tat org.flywaydb.core.internal.info.MigrationInfoImpl.lambda$validate$0(MigrationInfoImpl.java:317)
```

This happens because [flyway 8.0.3](https://flywaydb.org/documentation/learnmore/releaseNotes#8.0.3) added an `ignoreMigrationPatterns(ValidatePattern... ignoreMigrationPatterns)` overload. `micronaut-inject-java` generates a mapping for both the CSV string and the object array, but the object array call happens to be last, therefore is the one that matters.

Creating this bug here mainly for documentation purposes. But I'd also be interested if there was a fix that I am not seeing because I can't think of an easy one.

### Steps To Reproduce

```yaml
# application.yaml
flyway:
  datasources:
    default:
      ignore-migration-patterns: "*:missing"
```

- creates branches A and B from main
- checkout branch A, create migration A, and start application to migrate
- checkout branch B, create migration B, and start application to migrate
  - note: branch B does not have migration A
  
### Workarounds

Unfortunately, we cannot use the deprecated `ignoreMissingMigrations` as a workaround, because `micronaut-inject-java` does not allow the setting of `@Deprecated` properties.

However, we can downgrade to a version of flyway that doesn't have that overload.

```gradle
constraints {
  implementation("org.flywaydb:flyway-core") {
    version {
      strictly "8.0.2"
    }
  }
}
```

Downgrading to a version of flyway that does not have `ignoreMissingMigrations` deprecated might allow us to set `ignore-missing-migrations: true` but I haven't tried that.

Also if there were a way to explicitly support a deprecated property in `micronaut-inject-java` that might work too.

### Environment Information

- io.micronaut.flyway:micronaut-flyway:5.1.2
- org.flywaydb:flyway-core:8.4.2

### Version

3.3.2

**Comment by alvarosanchez** [comment]
This should be able to be fixed by adding a method to `FlywayConfigurationProperties` that takes a String and calls the corresponding method in Flyway's `FluentConfiguration`. Similar to what is done here:

https://github.com/micronaut-projects/micronaut-flyway/blob/master/flyway/src/main/java/io/micronaut/flyway/FlywayConfigurationProperties.java#L176-L181

**Comment by ivanmartinvalle** [comment]
@alvarosanchez : oh awesome!

Is this something I should make a PR for, or were you already planning on fixing it?

**Comment by alvarosanchez** [comment]
Generally speaking, when a core developer intends to work on an issue, they will assign it to themselves. So no, it's not on my short-term list. I just wanted to provide a hint to whoever could work on a fix.

If you are able to submit a PR, that would be fantastic!
