### ISSUE TITLE
Release new version with GraalVM support

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-flyway#42]
Can we release new version with GraalVM support and include it in Micronaut BOM, please?

**Comment by ilopmar** [comment]
I'm on it. Please give me a few minutes... :pray:

**Comment by morki** [comment]
Sorry, I was waiting for this and I am so excited to test it in action :)

**Comment by ilopmar** [comment]
Don't worry. `2.0.0.M2` released on Bintray. Waiting for the job to upload to Maven Central finishes.

You can also see the automatic PR to update the BOM: https://github.com/micronaut-projects/micronaut-core/pull/3445

**Comment by ilopmar** [comment]
@morki Btw, make sure you read the documentation to configure everything properly: https://micronaut-projects.github.io/micronaut-flyway/2.0.x/guide/index.html#graalvm

**Comment by morki** [comment]
@ilopmar thank you, I already read it in your PR :)
