### ISSUE TITLE
Configured baseline version not working

### ISSUE THREAD

**Issue by francisf2** [micronaut-projects/micronaut-flyway#458]
### Expected Behavior

Specified baseline version is 0.0, expect baseline version to be 0.0 and all migrations to be run against non-empty database on first execution.

### Actual Behaviour

Baseline version is initialized as 1, first migration is skipped.

### Steps To Reproduce

application.yml:

```
flyway:
  datasources:
    default:
      baseline-on-migrate: true
      baseline-version: 0.0
      enabled: true
      table: flyway_app
```

Migration files:
* V1__table.sql
* V2__add_column.sql
 
Log output:

```
Oct 03, 2023 1:45:39 PM org.flywaydb.core.internal.license.VersionPrinter printVersionOnly
INFO: Flyway Community Edition 9.22.1 by Redgate
Oct 03, 2023 1:45:39 PM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO: See release notes here: https://rd.gt/416ObMi
Oct 03, 2023 1:45:39 PM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO: 
Oct 03, 2023 1:45:39 PM org.flywaydb.core.FlywayExecutor execute
INFO: Database: jdbc:postgresql://postgres.local:5432/db (PostgreSQL 13.10)
Oct 03, 2023 1:45:40 PM org.flywaydb.core.internal.command.DbValidate validate
INFO: Successfully validated 3 migrations (execution time 00:00.090s)
Oct 03, 2023 1:45:40 PM org.flywaydb.core.internal.command.DbMigrate migrateGroup
INFO: Current version of schema "public": 1
Oct 03, 2023 1:45:40 PM org.flywaydb.core.internal.command.DbMigrate doMigrateGroup
INFO: Migrating schema "public" to version "2 - add column"
...
```

### Environment Information

PostgreSQL 13.10

JDK 17

micronautVersion=4.1.2
micronautApplicationVersion=4.1.1
micronautDataVersion=4.1.2
micronautFlywayVersion=6.2.0
micronautSqlVersion=5.0.1

The most recent versions with expected behaviour are:

micronautVersion=3.10.1
micronautApplicationVersion=3.7.10
micronautDataVersion=3.10.0
micronautFlywayVersion=5.5.0
micronautSqlVersion=4.8.1

### Version

4.1.2

**Comment by sdelamo** [comment]
do you have a sample app @francisf2 ?

**Comment by tPeltola** [comment]
I encountered this as well when upgrading to Micronaut 4.x. Because of other things, we did not need the baseline in the end, but I did manage to debug this a bit and found that  `$FlywayConfigurationProperties$Definition` has a (decompiled) line `this.getValueForPath(var1, var2, Argument.of(MigrationVersion.class, "baselineVersion"), "flyway.datasources.*.baseline-version");`. There is no converter for `MigrationVersion`, so even though the configuration property is found, it cannot be converted to the requested type.

**Comment by jeremyg484** [comment]
I'm looking at adding TypeConverters where it makes sense for the various configuration classes.

In the meantime (and in the future for any configuration types where we either don't have a converter yet, or where it just might not be possible to implement one), you can work around this by writing your own `BeanCreatedEventListener` such as:

```
import io.micronaut.context.event.BeanCreatedEvent;
import io.micronaut.context.event.BeanCreatedEventListener;
import io.micronaut.core.annotation.NonNull;
import jakarta.inject.Singleton;

@Singleton
public class FlywayConfigurationPropertiesListener implements BeanCreatedEventListener<FlywayConfigurationProperties> {

    @Override
    public FlywayConfigurationProperties onCreated(@NonNull BeanCreatedEvent<FlywayConfigurationProperties> event) {
        FlywayConfigurationProperties props = event.getBean();
        props.getFluentConfiguration().baselineVersion("0.0");
        return props;
    }
}
```
