### ISSUE TITLE
Cannot use with Oracle 23c

### ISSUE THREAD

**Issue by aalmiray** [micronaut-projects/micronaut-flyway#486]
### Issue description

Recent versions of Flyway (`10.x`) require an additional dependency to successfully connect to Oracle Database 23c. This additional dependency is found in this project's library dependencies

https://github.com/search?q=repo%3Amicronaut-projects%2Fmicronaut-flyway%20oracle&type=code

But it's not provided by its BOM nor its use is documented in this project.

**Comment by jeremyg484** [comment]
@aalmiray Thanks for pointing out the missing info in the docs. I have added it in #497. 

We do include these database-specific libraries in micronaut-flyway-bom (see for example https://repo1.maven.org/maven2/io/micronaut/flyway/micronaut-flyway-bom/7.0.0/micronaut-flyway-bom-7.0.0.pom).
