### ISSUE TITLE
Flyway doesn't pick up migrations in a native image

### ISSUE THREAD

**Issue by adamkobor** [micronaut-projects/micronaut-flyway#81]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Check out the example application
2. Run `./gradlew shadowJar`
3. Build a native image with `./docker-build.sh`
4. Run the native image with docker and watch the logs

### Expected Behaviour

Migrations should have been picked up by Flyway.

### Actual Behaviour

The following exception is thrown:
```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Unable to obtain inputstream for resource: db/migration/V1__Test.sql
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

### Example Application

https://github.com/kuvasz-uptime/kuvasz

The migrations are working like a charm if I build a docker image with openjdk, or I run the application with Gradle.

**Comment by adamkobor** [comment]
FYI - I cannot reproduce it after this commit I've made in the project: https://github.com/kuvasz-uptime/kuvasz/commit/677a91d020744243764ec6a294777fdbe9334199

**Comment by ilopmar** [comment]
@adamkobor have you checked the documentation about how to configure the application for GraalVM? https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html#graalvm

We have tests applications and this definitely works.

**Comment by adamkobor** [comment]
@ilopmar yes, I was aware of that, but I cannot reproduce the issue anymore. Maybe something have been stuck between builds, or something like that.

**Comment by ilopmar** [comment]
Closing the issue. If you can reproduce it again please file a new open.
