### ISSUE TITLE
Migrating several schemas using the `schemas` property only migrates the first schema in the list

### ISSUE THREAD

**Issue by runarhk** [micronaut-projects/micronaut-flyway#91]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone demo project and run the application. Notice how output from startup specifies that only the first schema is migrated:

```
13:11:35.310 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
13:11:35.488 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
13:11:35.507 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [default]
13:11:35.508 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 6.4.4 by Redgate
13:11:35.530 [main] INFO  o.f.c.i.database.DatabaseFactory - Database: jdbc:h2:mem:orgdb (H2 1.4)
13:11:35.577 [main] INFO  o.f.c.internal.database.base.Schema - Creating schema "flyway_history_schema" ...
13:11:35.578 [main] INFO  o.f.c.internal.database.base.Schema - Creating schema "test" ...
13:11:35.586 [main] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table "flyway_history_schema"."flyway_schema_history" ...
13:11:35.641 [main] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "flyway_history_schema": null
13:11:35.645 [main] INFO  o.f.core.internal.command.DbMigrate - Migrating schema "flyway_history_schema" to version 1 - create tables
13:11:35.676 [main] INFO  o.f.core.internal.command.DbMigrate - Successfully applied 1 migration to schema "flyway_history_schema" (execution time 00:00.044s)
13:11:35.963 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1361ms. Server Running: http://localhost:8080
```

### Expected Behaviour

All schemas in the list of schemas should be migrated. Ideally not the main schema as this should only hold firefly state tables. 

### Actual Behaviour

The first schema in the comma separated list of schemas are migrated

### Environment Information

- **Operating System**: Linux Mint 19.3 Cinnamon
- **Micronaut Version:** 2.0.1 with Micronaut flyway 2.0.0
- **JDK Version:** openjdk 11.0.8 2020-07-14

### Example Application
https://github.com/runarhk/mn_flyway_schemas_migration

**Comment by jonasgeiregat** [comment]
I believe this issue can be closed as this is completely flyway related and as far as I can see normal behavior.
The _schemas_ properties is there to manage the creation of the schemas not to apply the migrations within every listed schema. 

As stated here: https://flywaydb.org/blog/multipleschemas, the parameter does not effect migrations.
